
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-playwright
spec:
  params:
    - name: projects
    - name: deps
    - name: cred-secret-name
  workspaces:
    - name: ws
    - name: test-results-ws
  steps:
    - name: run-tests
      image: mcr.microsoft.com/playwright:v1.27.1-focal
      env:
        - name: CI
          value: "1"
        - name: TEST_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.cred-secret-name)
              key: TEST_USERNAME
        - name: TEST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.cred-secret-name)
              key: TEST_PASSWORD
      script: |
                # Multiple instances of this task can share a workspace
                # Create a private copy of the git repo including the tests

                tmpdir=$(mktemp -d)
                cp -R $(workspaces.ws.path)/. "$tmpdir"
                cd "$tmpdir"

                npm ci
                npx playwright install --with-deps "$(params.deps)"
                ret=0
                npx playwright test --project "$(params.projects)" || ret="$?"
                
                ls -l
                mv playwright-report "$(workspaces.test-results-ws.path)"
                mv test-results "$(workspaces.test-results-ws.path)"

                exit "$ret"
